# Generated by Django 2.2.2 on 2019-06-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='top_colors',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='colors.ColorPalette'),
        ),
    ]
